version: '3.8'

services:
  postgres:
    container_name: ecom-postgres
    image: postgres:16-alpine
    ports:
      - 5442:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: myapp