import { test, expect } from "@playwright/test";

const timestamp = Date.now();
const TEST_PRODUCT = {
  title: `E2E Product ${timestamp}`,
  description: "Automated test product created by e2e",
  price: 150000,
  regularPrice: 200000,
};

const TEST_IMAGE = {
  fileName: "test-product.jpg",
  url: "https://picsum.photos/id/26/720/446",
};

test.describe.serial("Admin create product with image", () => {
  let productId: string;

  test("admin login, create product, and add image", async ({ page }) => {
    // 1. Login as admin
    await page.goto("/admin/login");
    await page.fill("#email", "cappuai@yopmail.com");
    await page.fill("#password", "Qwerty@123");
    await page.getByRole("button", { name: /sign in/i }).click();

    await expect(page.getByRole("heading", { name: "Orders" })).toBeVisible({
      timeout: 15_000,
    });

    // 2. Create product via API (using browser session cookies)
    const createResult = await page.evaluate(async (product) => {
      const res = await fetch("/api/v1/admin/products", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(product),
      });
      return { status: res.status, body: await res.json() };
    }, TEST_PRODUCT);

    expect(createResult.status).toBe(200);
    productId = createResult.body.id;
    expect(productId).toBeTruthy();
    console.log(`Product created: ${productId}`);

    // 3. Add image to product via API
    const imageResult = await page.evaluate(
      async ({ productId, image }) => {
        const res = await fetch(`/api/v1/admin/products/${productId}/images`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            files: [{ fileName: image.fileName, url: image.url }],
          }),
        });
        return { status: res.status, body: await res.json() };
      },
      { productId, image: TEST_IMAGE },
    );

    expect(imageResult.status).toBe(200);
    console.log(`Image added to product ${productId}`);
  });

  test("verify product detail page with image", async ({ page }) => {
    expect(productId).toBeTruthy();

    // Product slug is generated by slugify(title.toLowerCase())
    const slug = TEST_PRODUCT.title.toLowerCase().replace(/\s+/g, "-");

    // 1. Navigate directly to the product detail page
    await page.goto(`/products/${slug}`);

    // 2. Verify product title
    await expect(
      page.getByRole("heading", { name: TEST_PRODUCT.title }),
    ).toBeVisible({ timeout: 15_000 });

    // 3. Verify price is displayed (formatted as "150.000" with dot separator)
    await expect(page.getByText("150.000")).toBeVisible({ timeout: 5_000 });

    // 4. Verify image is displayed
    const productImage = page.locator("img").first();
    await expect(productImage).toBeVisible({ timeout: 5_000 });
    console.log("Product detail page loaded with correct price and image");
  });
});
